# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ef326116e126e0fd011632791517b063b9243e69b215e879bb122801e0a04db6e636d6f5713ad3b73f59c615a60025ead26cb0c3720cc8a1c44a27eb18a3182

test:
  secret_key_base: c9d609e18fa3c586278994b6bbca3d52af9cd384a77dcfff36be9a570b3880d2438e6ddb100ce06bdaff2aefea965be7e747a445c686585e11bd8d4ad040681c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 271c90c9c21dc92abec0cd97e05f73e10a2fa1bde29a544d8656ccd687f84fccafb4f88007c46e7d67db019ef21683c9a5d384e4b83d24d46e66e2b49d9d30ba  
#<%= ENV["SECRET_KEY_BASE"] %>
